### ISSUE TITLE
Add "Forgot Password" to Login Page

### ISSUE THREAD

**Issue by MmyTohsaka** [KanakaXVII/CS-546-WS-2023-Group-53#20]
We need a way for users to change their password if they can't remember the old one. I believe this can be done using the DB functions I've already created. This would just require a new login page route and a slight modification to the `login.handlebars` to include the button.

**Comment by mekhtear** [comment]
this was a little tricky, please double check the code before merging

**Comment by MmyTohsaka** [comment]
[This PR](https://github.com/KanakaXVII/CS-546-WS-2023-Group-53/pull/24) covered the front-end of this task. [This PR](https://github.com/KanakaXVII/CS-546-WS-2023-Group-53/pull/25) is working on the backend operation for this.

**Comment by MmyTohsaka** [comment]
I made the changes I requested in the backend. Opening PR.

**Comment by MmyTohsaka** [comment]
Closing this because both PRs have been merged.
