### ISSUE TITLE
Logout process

### ISSUE THREAD

**Issue by princepethanii** [KanakaXVII/CS-546-WS-2023-Group-53#40]
We need to create a logout system as well. I have put a logout button in the navbar on all the pages where the user is logged in.

**Comment by MmyTohsaka** [comment]
@princepethanii Since the navbar be on all authenticated pages by default? If so, wouldn't the logout button in the navbar be sufficient without additional buttons on each page?

**Comment by MmyTohsaka** [comment]
Taking this task since it is still not done.
